export type Recipe = {
  slug: string;
  title: string;
  description: string;
  prepTime?: string;
  cookTime?: string;
  servings?: string;
  ingredients: string[];
  steps: string[];
  image?: string;
};

export const recipes: Recipe[] = [
  {
    slug: "steak-shrimp-lobster-sauce",
    title: "Steak with Shrimp and Lobster Sauce",
    description: "Filet mignon with a rich shrimp and lobster cream sauce.",
    servings: "2",
    image: "/recipes/steak-shrimp-lobster-sauce.png",
    ingredients: [
      "Steak: 2 (8–10 oz) filet mignon steaks 1½–2 inches thick",
      "garlic powder",
      "onion powder",
      "salt",
      "pepper",
      "1 tbsp olive oil",
      "2 tbsp unsalted butter",
      "4 thyme sprigs",
      "2 garlic cloves",
      "Shrimp & Lobster Sauce: 2 medium lobster tails, shell removed, cut into 1-inch pieces",
      "1 lb large shrimp, peeled, deveined, tail off",
      "all-purpose seasoning (salt, pepper, paprika, garlic powder, onion powder)",
      "1 tbsp olive oil",
      "8 tbsp unsalted butter",
      "¼ cup clam juice",
      "⅓ cup dry white wine",
      "1½ cup heavy cream",
      "½ tsp salt",
      "½ tsp pepper",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "1½ tsp smoked paprika",
    ],
    steps: [
      "Steak: On a cutting board, season steak on each side with salt, pepper, garlic powder and onion powder.",
      "Heat a cast iron skillet over medium-high heat. Add 1 tbsp olive oil. Once hot, add steaks and press down. After 2 minutes, add butter, garlic cloves and thyme. Cook 3 more minutes, then flip and cook 4 minutes on the other side.",
      "Reduce heat to medium and spoon butter over steak until 5°F below desired temp (see notes). Rest at least 10 minutes before serving.",
      "Shrimp & Lobster Sauce: Season shrimp with all-purpose seasoning in a bowl. In a 10-inch skillet, heat olive oil and 1 tbsp butter over medium. Sear shrimp 2 min one side, 1 min other side; remove and set aside. Add 1 tbsp butter, then lobster; sauté until pink, about 3 min; remove and set aside.",
      "Add 6 tbsp butter to skillet. When melting, add white wine and clam juice; bring to simmer. Whisk in heavy cream and bring to simmer. Stir in salt, pepper, garlic powder, onion powder, smoked paprika. Reduce to medium-low; simmer 10 min, stirring occasionally. Taste for salt.",
      "Stir in shrimp and lobster; simmer 1–2 min. Serve over cooked steak.",
      "Notes: Medium rare = 130–135°F. Steak will rise ~5°F while resting.",
    ],
  },
  {
    slug: "cream-soup-base-mix",
    title: "Homemade Cream Soup Base Mix",
    description: "Pantry staple equivalent to 6 cans of cream soup. Use for cream of chicken, celery, mushroom, broccoli cheese, or plain cheese.",
    image: "/recipes/cream-soup-base-mix.webp",
    ingredients: [
      "2 cups powdered milk",
      "¾ cup cornstarch",
      "2 tbsp chicken bouillon powder",
      "1 tsp onion powder",
      "½ tsp thyme",
      "½ tsp parsley",
      "½ tsp basil",
      "½ tsp black pepper",
    ],
    steps: [
      "Measure ingredients into your storage container. Shake well to combine.",
      "Store in a cool, dark place in an airtight container for up to 3 months, or in freezer for up to a year.",
      "To use: Add ⅓ cup mix to every 1¼ cups water. In a saucepan, heat over medium heat, whisking constantly; bring to a boil and cook 2 minutes.",
      "Cream of Chicken: Use chicken broth instead of water.",
      "Cream of Celery: Add ¼ cup finely diced celery.",
      "Cream of Mushroom: Add ½ cup finely diced fresh mushrooms.",
      "Cream of Broccoli Cheese: Add ½ cup diced cooked broccoli and 1 cup shredded cheddar.",
      "Cream of Cheese: Add 1 cup shredded cheddar cheese.",
    ],
  },
  {
    slug: "pasta-chicken-broccoli",
    title: "Pasta with Chicken and Broccoli",
    description: "Bow tie pasta with chicken, broccoli, and sun-dried tomatoes in a white wine and broth sauce.",
    image: "/recipes/pasta-chicken-broccoli.png",
    ingredients: [
      "4 tbsp extra virgin olive oil",
      "2 garlic cloves, finely chopped",
      "½–1 lb boneless, skinless chicken breasts, cut into ½-inch strips",
      "1½ cups small broccoli florets",
      "¾ cup sun-dried tomatoes, thinly sliced",
      "1 tsp dried basil",
      "Pinch crushed red pepper flakes",
      "Salt and pepper to taste",
      "¼ cup dry white wine",
      "¾ cup chicken broth",
      "1 tbsp butter or margarine",
      "½ lb bow tie pasta (farfalle), cooked and drained",
      "Grated Parmesan cheese",
    ],
    steps: [
      "Heat olive oil in a large skillet over medium. Add garlic and sauté about 1 minute until golden.",
      "Add chicken strips and sauté until white and almost cooked through.",
      "Add broccoli and sauté until crisp-tender. Add sun-dried tomatoes, basil, red pepper flakes, salt, and pepper.",
      "Pour in white wine, then add chicken broth and butter. Cook 3–5 minutes until heated through, stirring occasionally.",
      "Toss with cooked pasta. Serve with grated Parmesan.",
    ],
  },
  {
    slug: "classic-lasagna",
    title: "Classic Lasagna Recipe",
    description: "Traditional lasagna with meat sauce, ricotta, and mozzarella.",
    cookTime: "~2 hours",
    image: "/recipes/classic-lasagna.png",
    ingredients: [
      "9–12 lasagna noodles",
      "1 lb ground beef or Italian sausage",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 (28 oz) can crushed tomatoes",
      "2 (6 oz) cans tomato paste",
      "2 (6.5 oz) cans tomato sauce",
      "½ cup water",
      "2 tbsp white sugar",
      "1½ tsp dried basil",
      "½ tsp fennel seeds",
      "1 tsp Italian seasoning",
      "1 tbsp salt, divided",
      "¼ tsp ground black pepper",
      "4 tbsp chopped fresh parsley, divided",
      "12 oz ricotta cheese",
      "1 egg",
      "¾ tsp salt",
      "¾ lb mozzarella, sliced",
      "¾ cup grated Parmesan",
    ],
    steps: [
      "Cook noodles per package directions. Rinse with cold water and drain.",
      "In a Dutch oven, cook beef/sausage, onion, and garlic until browned. Stir in crushed tomatoes, tomato paste, tomato sauce, water. Season with sugar, basil, fennel, Italian seasoning, 1 tbsp salt, pepper, 2 tbsp parsley. Simmer covered ~1½ hours, stirring occasionally.",
      "Combine ricotta with egg, remaining 2 tbsp parsley, and ¾ tsp salt.",
      "Preheat oven to 375°F. In a 9×13 dish: spread 1½ cups meat sauce; layer 6 noodles; spread half of ricotta; top with ⅓ of mozzarella; 1½ cups meat sauce; ¼ cup Parmesan. Repeat layers; top with remaining mozzarella and Parmesan. Cover with foil (spray foil or keep it off the cheese).",
      "Bake 25 min. Remove foil; bake 25 min more. Cool 15 min before serving.",
    ],
  },
  {
    slug: "annies-favorite-pancakes",
    title: "Annie's Favorite Pancakes (Blueberry and Chocolate Chip)",
    description: "Fluffy pancakes with blueberries and chocolate chips.",
    image: "/recipes/annies-favorite-pancakes.png",
    ingredients: [
      "1½ cups all-purpose flour",
      "3½ tsp baking powder",
      "1 tbsp sugar",
      "¼ tsp salt",
      "1¼ cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "½ tsp vanilla extract",
      "½ cup blueberries (fresh or frozen)",
      "½ cup chocolate chips",
    ],
    steps: [
      "Sift together flour, baking powder, sugar, and salt in a large bowl.",
      "In another bowl, beat milk, egg, melted butter, and vanilla. Pour into dry ingredients and stir until just combined; a few lumps are fine.",
      "Gently fold in blueberries and chocolate chips.",
      "Preheat a lightly oiled griddle or pan over medium-high. Pour ~¼ cup batter per pancake. Cook until bubbles form, then flip and cook until golden.",
      "Serve hot with syrup or toppings.",
    ],
  },
  {
    slug: "french-toast",
    title: "French Toast Recipe",
    description: "Classic French toast with cinnamon and vanilla. Serve with maple syrup and berries.",
    image: "/recipes/french-toast.webp",
    ingredients: [
      "4 slices thick bread (brioche or challah)",
      "2 large eggs",
      "½ cup milk",
      "¼ tsp ground cinnamon",
      "1 tsp vanilla extract",
      "Butter or oil for frying",
      "Maple syrup, powdered sugar, fresh berries (optional)",
    ],
    steps: [
      "In a shallow dish, beat eggs. Add milk, cinnamon, and vanilla; mix well.",
      "Dip each bread slice in the egg mixture, a few seconds per side.",
      "Heat skillet over medium-high; add butter or oil. Cook soaked bread until golden, 2–3 min per side.",
      "Serve with maple syrup; optionally dust with powdered sugar and top with berries.",
    ],
  },
  {
    slug: "monkey-bread-muffin-tins",
    title: "Monkey Bread with Pillsbury Crescent Dough in Muffin Tins",
    description: "Individual cinnamon-sugar monkey bread cups using crescent dough.",
    image: "/recipes/monkey-bread-muffin-tins.webp",
    ingredients: [
      "2 cans Pillsbury Crescent Dough",
      "1 cup granulated sugar",
      "2 tsp cinnamon",
      "½ cup butter, melted",
      "½ cup brown sugar",
    ],
    steps: [
      "Preheat oven to 350°F. Grease muffin tins well.",
      "Open crescent dough and cut into ~1-inch pieces.",
      "Mix granulated sugar and cinnamon in a bowl. Roll each dough piece in the mixture.",
      "Place 3–4 coated pieces in each muffin cup.",
      "Mix melted butter and brown sugar. Spoon a little over the dough in each cup.",
      "Bake 12–15 min until golden and cooked through. Cool briefly in tins, then remove. Serve warm.",
    ],
  },
  {
    slug: "brownies",
    title: "Brownies",
    description: "Classic fudgy brownies with optional chocolate chips.",
    image: "/recipes/brownies.webp",
    ingredients: [
      "½ cup (115g) unsalted butter, melted",
      "1 cup (200g) granulated sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "½ cup (65g) all-purpose flour",
      "⅓ cup (35g) unsweetened cocoa powder",
      "¼ tsp baking powder",
      "¼ tsp salt",
      "½ cup (90g) chocolate chips (optional)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9×9 inch pan.",
      "Whisk melted butter and sugar. Add eggs and vanilla; mix well.",
      "In another bowl, sift flour, cocoa, baking powder, salt. Fold into wet mixture until just combined. Fold in chocolate chips if using.",
      "Pour into pan; smooth top. Bake 20–25 min until a toothpick has a few moist crumbs.",
      "Cool in pan, then cut into squares.",
    ],
  },
  {
    slug: "chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    description: "Classic soft chocolate chip cookies.",
    image: "/recipes/chocolate-chip-cookies.webp",
    ingredients: [
      "1 cup (2 sticks) unsalted butter, softened",
      "¾ cup granulated sugar",
      "¾ cup packed brown sugar",
      "1 tsp vanilla extract",
      "2 large eggs",
      "2¼ cups all-purpose flour",
      "1 tsp baking soda",
      "½ tsp salt",
      "2 cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 375°F.",
      "Beat butter, both sugars, and vanilla until creamy. Add eggs one at a time, beating after each.",
      "Whisk flour, baking soda, salt in another bowl. Gradually blend into creamed mixture. Stir in chocolate chips.",
      "Drop rounded tablespoonfuls onto ungreased baking sheets. Bake 9–11 min until golden.",
      "Cool on sheets 2 min; transfer to wire rack to cool completely.",
    ],
  },
  {
    slug: "sweet-sour-pork",
    title: "Sweet and Sour Pork",
    description: "Stir-fried pork with sweet-sour sauce, peppers, and pineapple.",
    servings: "2–4",
    image: "/recipes/sweet-sour-pork.webp",
    ingredients: [
      "1 lb lean boneless pork butt, 1-inch cubes",
      "1 cup water",
      "1 slice fresh ginger",
      "1 tbsp soy sauce",
      "1 egg",
      "¼ cup cornstarch",
      "4 tbsp salad oil",
      "1 medium onion, cut into wedges, layers separated",
      "1 green pepper, seeded, 1-inch squares",
      "1 clove garlic, minced",
      "2 small tomatoes, wedged",
      "½ cup canned pineapple chunks, drained",
      "Sweet-sour sauce: ¾ cup water, 1 tbsp each cornstarch, ketchup, soy sauce, ¼ cup sugar, wine vinegar, few drops liquid hot pepper seasoning",
    ],
    steps: [
      "Place pork, water, ginger, soy in a pan; bring to boil. Cover, reduce heat, simmer 5 min. Drain and cool. Make sweet-sour sauce; set aside.",
      "Beat egg. Put cornstarch in a bag. Dip pork in egg, then shake in cornstarch; shake off excess.",
      "Heat 2 tbsp oil in wok or wide pan over medium-high. Add meat (in batches if needed); stir-fry 2–3 min until browned. Remove meat; discard drippings.",
      "High heat; add remaining 2 tbsp oil. Add onion, green pepper, garlic; stir-fry 1 min. Add a little water if dry. Stir in sweet-sour sauce; cook until it boils and thickens slightly.",
      "Stir in tomatoes, pineapple, and meat; heat through ~30 sec. Serve.",
    ],
  },
  {
    slug: "green-pepper-steak",
    title: "Green Pepper Steak",
    description: "Beef strips with peppers, celery, and tomatoes in a soy-ginger sauce.",
    servings: "4",
    image: "/recipes/green-pepper-steak.webp",
    prepTime: "20 min",
    cookTime: "30–40 min",
    ingredients: [
      "1 lb beef chuck or round, fat trimmed",
      "¼ cup soy sauce",
      "1 clove garlic",
      "1½ tsp grated fresh ginger (or ½ tsp ground)",
      "1½ cup salad oil",
      "1 cup green onion, thinly sliced",
      "1 cup red or green peppers, 1-inch squares",
      "2 stalks celery, thinly sliced",
      "1 tbsp cornstarch",
      "1 cup water",
      "2 tomatoes, cut into wedges",
    ],
    steps: [
      "Cut beef across the grain into thin strips, ⅛-inch thick. Toss with soy sauce, garlic, ginger; set aside while you prep vegetables.",
      "Heat oil in large pan or wok. Add beef; toss over high heat until browned. If not tender, cover and simmer 30–40 min over low heat.",
      "Turn heat up; add vegetables. Toss until tender-crisp, ~10 min.",
      "Mix cornstarch with water; add to pan. Stir and cook until thickened. Add tomatoes and heat through. Serve.",
    ],
  },
  {
    slug: "sandwich-bread",
    title: "Sandwich Bread",
    description: "Soft loaf bread made with a stand mixer. Fits a 4×9-inch loaf pan.",
    image: "/recipes/sandwich-bread.webp",
    ingredients: [
      "3½ cups bread flour",
      "2 tbsp sugar",
      "1½ tsp salt",
      "1 packet (2¼ tsp) instant yeast",
      "1¼ cups warm water",
      "3 tbsp melted butter",
    ],
    steps: [
      "Attach dough hook to stand mixer. In bowl, combine flour, sugar, salt, yeast. With mixer on low, add warm water and melted butter. Mix until dough forms.",
      "Mix on medium 7–8 min until smooth and dough pulls away from bowl.",
      "Transfer to greased bowl; cover with damp cloth. Rise in a warm place until doubled, ~1 hour.",
      "Punch down; shape into a log to fit 4×9-inch loaf pan. Grease pan; place dough in pan. Cover; rise until nearly doubled, ~30–45 min.",
      "Preheat oven to 375°F. Bake 25–30 min until golden and loaf sounds hollow when tapped.",
      "Cool in pan 10 min, then turn out onto wire rack to cool before slicing.",
    ],
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getAllRecipes(): Recipe[] {
  return [...recipes];
}
