export type Recipe = {
  slug: string;
  title: string;
  description: string;
  prepTime?: string;
  cookTime?: string;
  servings?: string;
  ingredients: string[];
  steps: string[];
  image?: string;
};

export const recipes: Recipe[] = [
  {
    slug: "steak-shrimp-lobster-sauce",
    title: "Steak with Shrimp and Lobster Sauce",
    description: "Filet mignon with a rich shrimp and lobster cream sauce.",
    servings: "2",
    image: "/recipes/steak-shrimp-lobster-sauce.png",
    ingredients: [
      "Steak: 2 (8–10 oz) filet mignon steaks 1½–2 inches thick",
      "garlic powder",
      "onion powder",
      "salt",
      "pepper",
      "1 tbsp olive oil",
      "2 tbsp unsalted butter",
      "4 thyme sprigs",
      "2 garlic cloves",
      "Shrimp & Lobster Sauce: 2 medium lobster tails, shell removed, cut into 1-inch pieces",
      "1 lb large shrimp, peeled, deveined, tail off",
      "all-purpose seasoning (salt, pepper, paprika, garlic powder, onion powder)",
      "1 tbsp olive oil",
      "8 tbsp unsalted butter",
      "¼ cup clam juice",
      "⅓ cup dry white wine",
      "1½ cup heavy cream",
      "½ tsp salt",
      "½ tsp pepper",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "1½ tsp smoked paprika",
    ],
    steps: [
      "Steak: On a cutting board, season steak on each side with salt, pepper, garlic powder and onion powder.",
      "Heat a cast iron skillet over medium-high heat. Add 1 tbsp olive oil. Once hot, add steaks and press down. After 2 minutes, add butter, garlic cloves and thyme. Cook 3 more minutes, then flip and cook 4 minutes on the other side.",
      "Reduce heat to medium and spoon butter over steak until 5°F below desired temp (see notes). Rest at least 10 minutes before serving.",
      "Shrimp & Lobster Sauce: Season shrimp with all-purpose seasoning in a bowl. In a 10-inch skillet, heat olive oil and 1 tbsp butter over medium. Sear shrimp 2 min one side, 1 min other side; remove and set aside. Add 1 tbsp butter, then lobster; sauté until pink, about 3 min; remove and set aside.",
      "Add 6 tbsp butter to skillet. When melting, add white wine and clam juice; bring to simmer. Whisk in heavy cream and bring to simmer. Stir in salt, pepper, garlic powder, onion powder, smoked paprika. Reduce to medium-low; simmer 10 min, stirring occasionally. Taste for salt.",
      "Stir in shrimp and lobster; simmer 1–2 min. Serve over cooked steak.",
      "Notes: Medium rare = 130–135°F. Steak will rise ~5°F while resting.",
    ],
  },
  {
    slug: "cream-soup-base-mix",
    title: "Homemade Cream Soup Base Mix",
    description: "Pantry staple equivalent to 6 cans of cream soup. Use for cream of chicken, celery, mushroom, broccoli cheese, or plain cheese.",
    image: "/recipes/cream-soup-base-mix.webp",
    ingredients: [
      "2 cups powdered milk",
      "¾ cup cornstarch",
      "2 tbsp chicken bouillon powder",
      "1 tsp onion powder",
      "½ tsp thyme",
      "½ tsp parsley",
      "½ tsp basil",
      "½ tsp black pepper",
    ],
    steps: [
      "Measure ingredients into your storage container. Shake well to combine.",
      "Store in a cool, dark place in an airtight container for up to 3 months, or in freezer for up to a year.",
      "To use: Add ⅓ cup mix to every 1¼ cups water. In a saucepan, heat over medium heat, whisking constantly; bring to a boil and cook 2 minutes.",
      "Cream of Chicken: Use chicken broth instead of water.",
      "Cream of Celery: Add ¼ cup finely diced celery.",
      "Cream of Mushroom: Add ½ cup finely diced fresh mushrooms.",
      "Cream of Broccoli Cheese: Add ½ cup diced cooked broccoli and 1 cup shredded cheddar.",
      "Cream of Cheese: Add 1 cup shredded cheddar cheese.",
    ],
  },
  {
    slug: "pasta-chicken-broccoli",
    title: "Pasta with Chicken and Broccoli",
    description: "Bow tie pasta with chicken, broccoli, and sun-dried tomatoes in a white wine and broth sauce.",
    image: "/recipes/pasta-chicken-broccoli.png",
    ingredients: [
      "4 tbsp extra virgin olive oil",
      "2 garlic cloves, finely chopped",
      "½–1 lb boneless, skinless chicken breasts, cut into ½-inch strips",
      "1½ cups small broccoli florets",
      "¾ cup sun-dried tomatoes, thinly sliced",
      "1 tsp dried basil",
      "Pinch crushed red pepper flakes",
      "Salt and pepper to taste",
      "¼ cup dry white wine",
      "¾ cup chicken broth",
      "1 tbsp butter or margarine",
      "½ lb bow tie pasta (farfalle), cooked and drained",
      "Grated Parmesan cheese",
    ],
    steps: [
      "Heat olive oil in a large skillet over medium. Add garlic and sauté about 1 minute until golden.",
      "Add chicken strips and sauté until white and almost cooked through.",
      "Add broccoli and sauté until crisp-tender. Add sun-dried tomatoes, basil, red pepper flakes, salt, and pepper.",
      "Pour in white wine, then add chicken broth and butter. Cook 3–5 minutes until heated through, stirring occasionally.",
      "Toss with cooked pasta. Serve with grated Parmesan.",
    ],
  },
  {
    slug: "classic-lasagna",
    title: "Classic Lasagna Recipe",
    description: "Traditional lasagna with meat sauce, ricotta, and mozzarella.",
    cookTime: "~2 hours",
    image: "/recipes/classic-lasagna.png",
    ingredients: [
      "9–12 lasagna noodles",
      "1 lb ground beef or Italian sausage",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 (28 oz) can crushed tomatoes",
      "2 (6 oz) cans tomato paste",
      "2 (6.5 oz) cans tomato sauce",
      "½ cup water",
      "2 tbsp white sugar",
      "1½ tsp dried basil",
      "½ tsp fennel seeds",
      "1 tsp Italian seasoning",
      "1 tbsp salt, divided",
      "¼ tsp ground black pepper",
      "4 tbsp chopped fresh parsley, divided",
      "12 oz ricotta cheese",
      "1 egg",
      "¾ tsp salt",
      "¾ lb mozzarella, sliced",
      "¾ cup grated Parmesan",
    ],
    steps: [
      "Cook noodles per package directions. Rinse with cold water and drain.",
      "In a Dutch oven, cook beef/sausage, onion, and garlic until browned. Stir in crushed tomatoes, tomato paste, tomato sauce, water. Season with sugar, basil, fennel, Italian seasoning, 1 tbsp salt, pepper, 2 tbsp parsley. Simmer covered ~1½ hours, stirring occasionally.",
      "Combine ricotta with egg, remaining 2 tbsp parsley, and ¾ tsp salt.",
      "Preheat oven to 375°F. In a 9×13 dish: spread 1½ cups meat sauce; layer 6 noodles; spread half of ricotta; top with ⅓ of mozzarella; 1½ cups meat sauce; ¼ cup Parmesan. Repeat layers; top with remaining mozzarella and Parmesan. Cover with foil (spray foil or keep it off the cheese).",
      "Bake 25 min. Remove foil; bake 25 min more. Cool 15 min before serving.",
    ],
  },
  {
    slug: "annies-favorite-pancakes",
    title: "Annie's Favorite Pancakes (Blueberry and Chocolate Chip)",
    description: "Fluffy pancakes with blueberries and chocolate chips.",
    image: "/recipes/annies-favorite-pancakes.png",
    ingredients: [
      "1½ cups all-purpose flour",
      "3½ tsp baking powder",
      "1 tbsp sugar",
      "¼ tsp salt",
      "1¼ cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "½ tsp vanilla extract",
      "½ cup blueberries (fresh or frozen)",
      "½ cup chocolate chips",
    ],
    steps: [
      "Sift together flour, baking powder, sugar, and salt in a large bowl.",
      "In another bowl, beat milk, egg, melted butter, and vanilla. Pour into dry ingredients and stir until just combined; a few lumps are fine.",
      "Gently fold in blueberries and chocolate chips.",
      "Preheat a lightly oiled griddle or pan over medium-high. Pour ~¼ cup batter per pancake. Cook until bubbles form, then flip and cook until golden.",
      "Serve hot with syrup or toppings.",
    ],
  },
  {
    slug: "french-toast",
    title: "French Toast Recipe",
    description: "Classic French toast with cinnamon and vanilla. Serve with maple syrup and berries.",
    image: "/recipes/french-toast.webp",
    ingredients: [
      "4 slices thick bread (brioche or challah)",
      "2 large eggs",
      "½ cup milk",
      "¼ tsp ground cinnamon",
      "1 tsp vanilla extract",
      "Butter or oil for frying",
      "Maple syrup, powdered sugar, fresh berries (optional)",
    ],
    steps: [
      "In a shallow dish, beat eggs. Add milk, cinnamon, and vanilla; mix well.",
      "Dip each bread slice in the egg mixture, a few seconds per side.",
      "Heat skillet over medium-high; add butter or oil. Cook soaked bread until golden, 2–3 min per side.",
      "Serve with maple syrup; optionally dust with powdered sugar and top with berries.",
    ],
  },
  {
    slug: "monkey-bread-muffin-tins",
    title: "Monkey Bread with Pillsbury Crescent Dough in Muffin Tins",
    description: "Individual cinnamon-sugar monkey bread cups using crescent dough.",
    image: "/recipes/monkey-bread-muffin-tins.webp",
    ingredients: [
      "2 cans Pillsbury Crescent Dough",
      "1 cup granulated sugar",
      "2 tsp cinnamon",
      "½ cup butter, melted",
      "½ cup brown sugar",
    ],
    steps: [
      "Preheat oven to 350°F. Grease muffin tins well.",
      "Open crescent dough and cut into ~1-inch pieces.",
      "Mix granulated sugar and cinnamon in a bowl. Roll each dough piece in the mixture.",
      "Place 3–4 coated pieces in each muffin cup.",
      "Mix melted butter and brown sugar. Spoon a little over the dough in each cup.",
      "Bake 12–15 min until golden and cooked through. Cool briefly in tins, then remove. Serve warm.",
    ],
  },
  {
    slug: "brownies",
    title: "Brownies",
    description: "Classic fudgy brownies with optional chocolate chips.",
    image: "/recipes/brownies.webp",
    ingredients: [
      "½ cup (115g) unsalted butter, melted",
      "1 cup (200g) granulated sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "½ cup (65g) all-purpose flour",
      "⅓ cup (35g) unsweetened cocoa powder",
      "¼ tsp baking powder",
      "¼ tsp salt",
      "½ cup (90g) chocolate chips (optional)",
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 9×9 inch pan.",
      "Whisk melted butter and sugar. Add eggs and vanilla; mix well.",
      "In another bowl, sift flour, cocoa, baking powder, salt. Fold into wet mixture until just combined. Fold in chocolate chips if using.",
      "Pour into pan; smooth top. Bake 20–25 min until a toothpick has a few moist crumbs.",
      "Cool in pan, then cut into squares.",
    ],
  },
  {
    slug: "chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    description: "Classic soft chocolate chip cookies.",
    image: "/recipes/chocolate-chip-cookies.webp",
    ingredients: [
      "1 cup (2 sticks) unsalted butter, softened",
      "¾ cup granulated sugar",
      "¾ cup packed brown sugar",
      "1 tsp vanilla extract",
      "2 large eggs",
      "2¼ cups all-purpose flour",
      "1 tsp baking soda",
      "½ tsp salt",
      "2 cups semi-sweet chocolate chips",
    ],
    steps: [
      "Preheat oven to 375°F.",
      "Beat butter, both sugars, and vanilla until creamy. Add eggs one at a time, beating after each.",
      "Whisk flour, baking soda, salt in another bowl. Gradually blend into creamed mixture. Stir in chocolate chips.",
      "Drop rounded tablespoonfuls onto ungreased baking sheets. Bake 9–11 min until golden.",
      "Cool on sheets 2 min; transfer to wire rack to cool completely.",
    ],
  },
  {
    slug: "sweet-sour-pork",
    title: "Sweet and Sour Pork",
    description: "Stir-fried pork with sweet-sour sauce, peppers, and pineapple.",
    servings: "2–4",
    image: "/recipes/sweet-sour-pork.webp",
    ingredients: [
      "1 lb lean boneless pork butt, 1-inch cubes",
      "1 cup water",
      "1 slice fresh ginger",
      "1 tbsp soy sauce",
      "1 egg",
      "¼ cup cornstarch",
      "4 tbsp salad oil",
      "1 medium onion, cut into wedges, layers separated",
      "1 green pepper, seeded, 1-inch squares",
      "1 clove garlic, minced",
      "2 small tomatoes, wedged",
      "½ cup canned pineapple chunks, drained",
      "Sweet-sour sauce: ¾ cup water, 1 tbsp each cornstarch, ketchup, soy sauce, ¼ cup sugar, wine vinegar, few drops liquid hot pepper seasoning",
    ],
    steps: [
      "Place pork, water, ginger, soy in a pan; bring to boil. Cover, reduce heat, simmer 5 min. Drain and cool. Make sweet-sour sauce; set aside.",
      "Beat egg. Put cornstarch in a bag. Dip pork in egg, then shake in cornstarch; shake off excess.",
      "Heat 2 tbsp oil in wok or wide pan over medium-high. Add meat (in batches if needed); stir-fry 2–3 min until browned. Remove meat; discard drippings.",
      "High heat; add remaining 2 tbsp oil. Add onion, green pepper, garlic; stir-fry 1 min. Add a little water if dry. Stir in sweet-sour sauce; cook until it boils and thickens slightly.",
      "Stir in tomatoes, pineapple, and meat; heat through ~30 sec. Serve.",
    ],
  },
  {
    slug: "green-pepper-steak",
    title: "Green Pepper Steak",
    description: "Beef strips with peppers, celery, and tomatoes in a soy-ginger sauce.",
    servings: "4",
    image: "/recipes/green-pepper-steak.webp",
    prepTime: "20 min",
    cookTime: "30–40 min",
    ingredients: [
      "1 lb beef chuck or round, fat trimmed",
      "¼ cup soy sauce",
      "1 clove garlic",
      "1½ tsp grated fresh ginger (or ½ tsp ground)",
      "1½ cup salad oil",
      "1 cup green onion, thinly sliced",
      "1 cup red or green peppers, 1-inch squares",
      "2 stalks celery, thinly sliced",
      "1 tbsp cornstarch",
      "1 cup water",
      "2 tomatoes, cut into wedges",
    ],
    steps: [
      "Cut beef across the grain into thin strips, ⅛-inch thick. Toss with soy sauce, garlic, ginger; set aside while you prep vegetables.",
      "Heat oil in large pan or wok. Add beef; toss over high heat until browned. If not tender, cover and simmer 30–40 min over low heat.",
      "Turn heat up; add vegetables. Toss until tender-crisp, ~10 min.",
      "Mix cornstarch with water; add to pan. Stir and cook until thickened. Add tomatoes and heat through. Serve.",
    ],
  },
  {
    slug: "sandwich-bread",
    title: "Sandwich Bread",
    description: "Soft loaf bread made with a stand mixer. Fits a 4×9-inch loaf pan.",
    image: "/recipes/sandwich-bread.webp",
    ingredients: [
      "3½ cups bread flour",
      "2 tbsp sugar",
      "1½ tsp salt",
      "1 packet (2¼ tsp) instant yeast",
      "1¼ cups warm water",
      "3 tbsp melted butter",
    ],
    steps: [
      "Attach dough hook to stand mixer. In bowl, combine flour, sugar, salt, yeast. With mixer on low, add warm water and melted butter. Mix until dough forms.",
      "Mix on medium 7–8 min until smooth and dough pulls away from bowl.",
      "Transfer to greased bowl; cover with damp cloth. Rise in a warm place until doubled, ~1 hour.",
      "Punch down; shape into a log to fit 4×9-inch loaf pan. Grease pan; place dough in pan. Cover; rise until nearly doubled, ~30–45 min.",
      "Preheat oven to 375°F. Bake 25–30 min until golden and loaf sounds hollow when tapped.",
      "Cool in pan 10 min, then turn out onto wire rack to cool before slicing.",
    ],
  },
  {
    slug: "restaurant-style-blended-salsa",
    title: "Restaurant-Style Blended Salsa",
    description: "Smooth blended salsa with tomatoes, jalapeño, cilantro, lime, and cumin. Best after sitting overnight.",
    prepTime: "10 min",
    servings: "About 3 cups",
    ingredients: [
      "1 lb 12 oz petite diced tomatoes",
      "¼ cup white or yellow onion, rough chopped",
      "½ to 1 jalapeño, seeds removed for mild salsa",
      "1 clove garlic",
      "Small handful cilantro",
      "1–2 tbsp lime juice",
      "½ tsp salt, plus more to taste",
      "Tiny pinch cumin (⅛ tsp)",
      "Optional pinch sugar, to balance acidity",
      "Red pepper flakes or red peppers, optional for more heat",
    ],
    steps: [
      "Add tomatoes, onion, jalapeño, garlic, cilantro, lime juice, salt, cumin, and sugar if using to a blender.",
      "Pulse 3–6 times on medium power, just until smooth but not completely pureed.",
      "Taste and adjust salt, lime juice, or heat. Substitute or add red peppers if you want it hotter.",
      "Refrigerate overnight before serving for the best flavor.",
    ],
  },
  {
    slug: "dutch-apple-pie",
    title: "Dutch Apple Crumble Pie Recipe",
    description:
      "This Dutch Apple Pie Recipe has the BEST apple flavor! A flaky, buttery crust on bottom, cooked apple filling in the center, and the most amazing golden-crisp, buttery crumb streusel topping! Adapted from traditional Apple Pie.",
    prepTime: "45 min",
    cookTime: "1 hr 20 min (+ 4 hr rest)",
    servings: "10",
    ingredients: [
      "1 homemade single pie crust (1 sheet of pie dough)",
      "For the apple filling: ¼ tsp lemon zest",
      "juice from half a lemon (2 tbsp, no more)",
      "5 lbs apples (before peeling and coring)",
      "½ cup brown sugar, packed",
      "½ cup granulated sugar",
      "⅓ cup all-purpose flour",
      "½ tsp kosher salt",
      "1½ tsp cinnamon",
      "¾ tsp nutmeg",
      "½ tsp cardamom (optional)",
      "1 tsp vanilla",
      "For the sugar crumble: 1½ cups all-purpose flour",
      "⅓ cup granulated sugar",
      "¾ cup brown sugar, packed",
      "½ tsp kosher salt (use a little less if using table salt)",
      "¾ cup butter, melted (1½ sticks)",
    ],
    steps: [
      "Choose your apples: you need 5 pounds (~11 large apples). Use a mix for best flavor — Granny Smith, Honeycrisp, and Golden Delicious work well.",
      "Make the filling: zest ¼ tsp lemon peel into a 12-inch high-sided skillet (heat off). Add juice from half a lemon (~2 tbsp). Don't use much more — just enough to wake up the apples and keep them from browning.",
      "Peel and slice apples into ⅛-inch pieces. Peel and slice one apple at a time, adding each to the pan with the lemon juice and stirring occasionally to coat. This keeps them from browning.",
      "Once all apples are in the pan, set it over medium heat. Add ½ cup packed brown sugar, ½ cup granulated sugar, ⅓ cup flour, ½ tsp kosher salt, 1½ tsp cinnamon, ¾ tsp nutmeg, and ½ tsp cardamom (optional). Stir gently so you don't break the apples.",
      "Once moistened with no patches of flour or cinnamon, cover and cook 20 minutes, stirring every 3 minutes and replacing the lid each time. Cook until apples are fork-tender but still hold their shape — they will not soften more in the oven. Taste and adjust time to your preferred doneness. If apples stick, add 1 tbsp water (plus more as needed); use sparingly.",
      "Remove from heat and stir in 1 tsp vanilla.",
      "Transfer the filling (including all the caramel sauce) to a half sheet pan or any pan with a lip. Spread to the edges. Cool completely in the fridge or freezer (~30 min in freezer, or a couple hours at room temperature in the pan).",
      "Roll out pie dough and place in a 9-inch pie dish. Fold edges underneath and crimp with your fingers and thumbs. Chill the crust in the fridge or freezer ~30 minutes.",
      "While the crust and filling chill, place a baking sheet or pizza stone on the center oven rack and preheat to 425°F for at least 20–30 minutes.",
      "Make the sugar crumble: in a medium bowl, whisk 1½ cups flour, ⅓ cup white sugar, ¾ cup packed brown sugar, and ½ tsp kosher salt. Melt ¾ cup butter (1½ sticks) and pour over the dry ingredients; stir gently until you have a wet sandy mixture with some large clumps. Chill in the fridge until assembly.",
      "When the filling is completely cooled and the pie shell is mostly frozen, scrape all the chilled filling into the pie shell — every last bit of the gooey filling.",
      "Break the crumble into smaller bite-size pieces with your hands or a fork. Top the pie with about 1–2 cups crumble (not all of it). Return the remaining crumble to the fridge.",
      "Bake: place the chilled pie on the hot baking sheet in the oven. Bake 15 minutes at 425°F until the crust edge is turning light brown.",
      "Meanwhile, make a foil shield: fold a square of foil the size of your pie in half twice, cut out the center, and open — or use a pie shield.",
      "After 15 minutes at 425°F, reduce heat to 350°F without removing the pie. Bake 10 more minutes at 350°F.",
      "Remove the pie from the oven and quickly shut the oven door. Sprinkle the remaining chilled crumble over the top, breaking up large pieces. Place the foil shield on the crust edges (center exposed). Confirm oven is at 350°F.",
      "Return the pie to the hot baking sheet and bake at 350°F for 25–35 more minutes (55–65 minutes total in the oven). Done when crust edges are brown and crumble is light golden brown in the center. For more color, remove the foil shield and bake another 5–10 minutes.",
      "Cool on a wire rack at least 4 hours before slicing — cutting early makes the filling too liquid and the crumble soggy.",
      "Once completely cool, slice and serve with vanilla ice cream and salted caramel sauce if desired.",
      "Store on the counter up to 2 days, covered with plastic wrap or foil; then refrigerate.",
      "Notes: cooled apple filling can be frozen in a ziplock bag up to 3 months for pies, cobblers, or apple crisp.",
      "Freezing Method 1: freeze crust, filling, and topping separately in freezer bags. Thaw in fridge, then assemble and bake per instructions.",
      "Freezing Method 2: assemble pie through the first crumble layer. Wrap pie (pan and all) in two layers each of plastic wrap and foil; freeze topping separately. Store upright 1–3 months. To bake: unwrap, preheat oven to 425°F with pizza stone or cookie sheet on center rack, then follow baking steps from adding the second crumble layer; add 15–20 min bake time and cover top with foil if browning too fast.",
      "Freezing Method 3: freeze fully baked pie after cooling 8 hours, wrapped well. To reheat: unwrap, preheat to 350°F with cookie sheet or pizza stone on center rack, bake ~30 min until warmed through; cover with foil if crust or crumble browns too much.",
    ],
  },
  {
    slug: "easy-refrigerator-dill-pickles",
    title: "Easy Refrigerator Dill Pickles",
    description:
      "Easy Refrigerator Dill Pickles take only a few minutes to make. Once you make your own homemade dill pickles, you'll never buy store bought again.",
    prepTime: "10 min",
    cookTime: "5 min",
    servings: "18 (~3 quart jars)",
    ingredients: [
      "12 pickling cucumbers (quantity can vary depending on size)",
      "4 cups water",
      "2 cups white vinegar",
      "2 tbsp kosher salt",
      "1 tsp sugar",
      "1 bunch fresh dill (amount can vary; thick stems removed)",
      "1 head garlic, skins removed, cloves smashed (use fewer if garlic is strong)",
      "1 tbsp peppercorn kernels (~10 peppercorns per jar)",
    ],
    steps: [
      "Prepare ingredients: thoroughly wash the pickling cucumbers. Slice into ¼-inch thick slices or spears and set aside. Smash garlic cloves and separate dill from thick stems. Sanitize mason jars by running them through the dishwasher.",
      "Prepare brine: combine water, white vinegar, kosher salt, and sugar in a medium saucepan. Bring to a boil and swirl the pan until sugar and salt dissolve. Remove from heat and cool to room temperature.",
      "Make the pickles: layer cucumbers with fresh dill, smashed garlic, and peppercorns in the jars. Don't pack too tight — leave room for the brine. Pour in enough brine to cover the cucumbers.",
      "Seal with an airtight lid and store in the refrigerator. Flavor is best after at least one week, but they can be eaten anytime. Pickles should keep at least 4–6 weeks in the fridge.",
      "Notes: quantities listed make about 3 quart-sized jars. Dill and garlic amounts can vary to taste — pack in as much or as little fresh dill as you like.",
      "If your garlic is particularly strong, use fewer cloves if you are sensitive to the taste.",
    ],
  },
  {
    slug: "lactaid-crunchy-rolls",
    title: "Lactaid Crunchy Rolls",
    description:
      "Crunchy crust rolls made with Lactaid milk. Lactaid is real milk with lactose broken down into glucose and galactose, so it tastes slightly sweeter than regular milk and helps the rolls brown beautifully—especially in a gas oven. Substitute Lactaid 1:1 for whole milk.",
    cookTime: "18–22 min",
    servings: "8–10 rolls",
    ingredients: [
      "500g bread flour",
      "200g Lactaid milk (warm, approx. 95°F / 35°C)",
      "125g water (warm, approx. 95°F / 35°C)",
      "30g unsalted butter (melted and cooled)",
      "15g sugar (reduced by 5g since Lactaid is naturally sweeter)",
      "10g fine sea salt",
      "5g instant yeast",
    ],
    steps: [
      "Knead: Mix all ingredients and knead for 10 minutes until smooth.",
      "Rise: Let the dough double in size (1 to 1.5 hours).",
      "Shape: Divide into 8–10 balls and let rise again for 45 minutes on your baking sheet.",
      "Bake with steam: Preheat your gas oven to 425°F (218°C) with an empty metal pan on the bottom rack. Slash the rolls, mist them with water, put them in, and pour 1 cup of boiling water into the bottom pan to create the steam needed for that crunchy crust. Bake for 18–22 minutes.",
    ],
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getAllRecipes(): Recipe[] {
  return [...recipes];
}
