import type { BrushCategory, BrushDef, CanvasPreset } from "./types";

export const CANVAS_PRESETS: CanvasPreset[] = [
  { id: "screen-4k", label: "Screen 4K", width: 3840, height: 2160, dpi: 72 },
  { id: "screen-hd", label: "Screen HD", width: 1920, height: 1080, dpi: 72 },
  { id: "ipad-pro-13", label: "iPad Pro 13\"", width: 2752, height: 2064, dpi: 264 },
  { id: "ipad-pro-11", label: "iPad Pro 11\"", width: 2388, height: 1668, dpi: 264 },
  { id: "ipad-air", label: "iPad Air", width: 2360, height: 1640, dpi: 264 },
  { id: "square-2048", label: "Square 2048", width: 2048, height: 2048, dpi: 132 },
  { id: "a4", label: "A4", width: 2480, height: 3508, dpi: 300 },
  { id: "4x6", label: "4 × 6 Photo", width: 1200, height: 1800, dpi: 300 },
];

export const CATEGORY_LABELS: Record<BrushCategory, string> = {
  sketching: "Sketching",
  inking: "Inking",
  painting: "Painting",
  artistic: "Artistic",
  calligraphy: "Calligraphy",
  textures: "Textures",
  elements: "Elements",
  imported: "Imported",
};

export const BRUSHES: BrushDef[] = [
  {
    id: "6b-pencil",
    name: "6B Pencil",
    category: "sketching",
    preview: "#8a8a8a",
    size: 12,
    opacity: 0.75,
    spacing: 0.08,
    flow: 0.85,
    hardness: 0.35,
    scatter: 0.15,
    streamline: 0.55,
    wetMix: 0,
    texture: "grain",
    taper: 0.4,
  },
  {
    id: "technical-pen",
    name: "Technical Pen",
    category: "sketching",
    preview: "#222",
    size: 4,
    opacity: 1,
    spacing: 0.04,
    flow: 1,
    hardness: 1,
    scatter: 0,
    streamline: 0.85,
    wetMix: 0,
    texture: "smooth",
    taper: 0.1,
  },
  {
    id: "soft-pencil",
    name: "Soft Graphite",
    category: "sketching",
    preview: "#666",
    size: 18,
    opacity: 0.5,
    spacing: 0.06,
    flow: 0.7,
    hardness: 0.2,
    scatter: 0.08,
    streamline: 0.45,
    wetMix: 0,
    texture: "grain",
    taper: 0.55,
  },
  {
    id: "studio-pen",
    name: "Studio Pen",
    category: "inking",
    preview: "#111",
    size: 8,
    opacity: 1,
    spacing: 0.03,
    flow: 1,
    hardness: 1,
    scatter: 0,
    streamline: 0.92,
    wetMix: 0,
    texture: "smooth",
    taper: 0.15,
  },
  {
    id: "monoline",
    name: "Monoline",
    category: "inking",
    preview: "#000",
    size: 6,
    opacity: 1,
    spacing: 0.02,
    flow: 1,
    hardness: 1,
    scatter: 0,
    streamline: 0.95,
    wetMix: 0,
    texture: "smooth",
    taper: 0,
  },
  {
    id: "dry-ink",
    name: "Dry Ink",
    category: "inking",
    preview: "#1a1a1a",
    size: 14,
    opacity: 0.9,
    spacing: 0.05,
    flow: 0.95,
    hardness: 0.85,
    scatter: 0.05,
    streamline: 0.75,
    wetMix: 0,
    texture: "speckle",
    taper: 0.25,
  },
  {
    id: "round-brush",
    name: "Round Brush",
    category: "painting",
    preview: "#3b82f6",
    size: 28,
    opacity: 0.85,
    spacing: 0.12,
    flow: 0.9,
    hardness: 0.55,
    scatter: 0,
    streamline: 0.35,
    wetMix: 0.15,
    texture: "smooth",
    taper: 0.3,
  },
  {
    id: "soft-airbrush",
    name: "Soft Airbrush",
    category: "painting",
    preview: "#ec4899",
    size: 48,
    opacity: 0.35,
    spacing: 0.08,
    flow: 0.55,
    hardness: 0.05,
    scatter: 0.12,
    streamline: 0.25,
    wetMix: 0.2,
    texture: "smooth",
    taper: 0.2,
  },
  {
    id: "watercolor",
    name: "Watercolor",
    category: "painting",
    preview: "#06b6d4",
    size: 36,
    opacity: 0.4,
    spacing: 0.1,
    flow: 0.45,
    hardness: 0.15,
    scatter: 0.08,
    streamline: 0.3,
    wetMix: 0.65,
    texture: "canvas",
    taper: 0.35,
  },
  {
    id: "oil-paint",
    name: "Oil Paint",
    category: "painting",
    preview: "#f59e0b",
    size: 32,
    opacity: 0.92,
    spacing: 0.14,
    flow: 0.88,
    hardness: 0.4,
    scatter: 0.04,
    streamline: 0.2,
    wetMix: 0.35,
    texture: "canvas",
    taper: 0.15,
  },
  {
    id: "charcoal",
    name: "Charcoal",
    category: "artistic",
    preview: "#333",
    size: 22,
    opacity: 0.65,
    spacing: 0.1,
    flow: 0.75,
    hardness: 0.25,
    scatter: 0.35,
    streamline: 0.15,
    wetMix: 0,
    texture: "grain",
    taper: 0.5,
  },
  {
    id: "pastel",
    name: "Pastel",
    category: "artistic",
    preview: "#a78bfa",
    size: 40,
    opacity: 0.55,
    spacing: 0.15,
    flow: 0.6,
    hardness: 0.1,
    scatter: 0.2,
    streamline: 0.1,
    wetMix: 0.1,
    texture: "grain",
    taper: 0.2,
  },
  {
    id: "splatter",
    name: "Splatter",
    category: "artistic",
    preview: "#ef4444",
    size: 24,
    opacity: 0.8,
    spacing: 0.35,
    flow: 0.7,
    hardness: 0.9,
    scatter: 0.85,
    streamline: 0,
    wetMix: 0,
    texture: "speckle",
    taper: 0,
  },
  {
    id: "script",
    name: "Script",
    category: "calligraphy",
    preview: "#111",
    size: 16,
    opacity: 1,
    spacing: 0.04,
    flow: 1,
    hardness: 0.95,
    scatter: 0,
    streamline: 0.88,
    wetMix: 0,
    texture: "smooth",
    taper: 0.6,
  },
  {
    id: "flat-marker",
    name: "Flat Marker",
    category: "calligraphy",
    preview: "#dc2626",
    size: 20,
    opacity: 0.95,
    spacing: 0.06,
    flow: 0.98,
    hardness: 0.7,
    scatter: 0,
    streamline: 0.5,
    wetMix: 0,
    texture: "smooth",
    taper: 0.1,
  },
  {
    id: "canvas-texture",
    name: "Canvas",
    category: "textures",
    preview: "#d4c4a8",
    size: 30,
    opacity: 0.5,
    spacing: 0.2,
    flow: 0.5,
    hardness: 0.3,
    scatter: 0.1,
    streamline: 0,
    wetMix: 0,
    texture: "canvas",
    taper: 0,
  },
  {
    id: "noise-grain",
    name: "Noise Grain",
    category: "textures",
    preview: "#888",
    size: 26,
    opacity: 0.45,
    spacing: 0.18,
    flow: 0.55,
    hardness: 0.2,
    scatter: 0.25,
    streamline: 0,
    wetMix: 0,
    texture: "speckle",
    taper: 0,
  },
  {
    id: "glitter",
    name: "Glitter",
    category: "elements",
    preview: "#fbbf24",
    size: 18,
    opacity: 0.9,
    spacing: 0.4,
    flow: 0.85,
    hardness: 1,
    scatter: 0.95,
    streamline: 0,
    wetMix: 0,
    texture: "speckle",
    taper: 0,
  },
  {
    id: "cloud",
    name: "Cloud",
    category: "elements",
    preview: "#e2e8f0",
    size: 56,
    opacity: 0.25,
    spacing: 0.2,
    flow: 0.4,
    hardness: 0.05,
    scatter: 0.15,
    streamline: 0.1,
    wetMix: 0.3,
    texture: "smooth",
    taper: 0.1,
  },
];

export const DEFAULT_PALETTES: { name: string; colors: string[] }[] = [
  {
    name: "Procreate Classic",
    colors: [
      "#000000",
      "#ffffff",
      "#ef4444",
      "#f97316",
      "#eab308",
      "#22c55e",
      "#06b6d4",
      "#3b82f6",
      "#8b5cf6",
      "#ec4899",
      "#78716c",
      "#a8a29e",
    ],
  },
  {
    name: "Warm Earth",
    colors: [
      "#1c1917",
      "#44403c",
      "#78716c",
      "#a8a29e",
      "#d6d3d1",
      "#fef3c7",
      "#fcd34d",
      "#f59e0b",
      "#ea580c",
      "#dc2626",
      "#92400e",
      "#451a03",
    ],
  },
  {
    name: "Ocean",
    colors: [
      "#0c4a6e",
      "#0369a1",
      "#0284c7",
      "#0ea5e9",
      "#38bdf8",
      "#7dd3fc",
      "#bae6fd",
      "#164e63",
      "#155e75",
      "#0891b2",
      "#06b6d4",
      "#67e8f9",
    ],
  },
  {
    name: "Pastel",
    colors: [
      "#fecdd3",
      "#fda4af",
      "#fbcfe8",
      "#f9a8d4",
      "#e9d5ff",
      "#ddd6fe",
      "#bfdbfe",
      "#bae6fd",
      "#a7f3d0",
      "#bbf7d0",
      "#fef08a",
      "#fde68a",
    ],
  },
];

export function getBrushesByCategory(category: BrushCategory): BrushDef[] {
  return BRUSHES.filter((b) => b.category === category);
}

export function findBrush(id: string): BrushDef {
  return BRUSHES.find((b) => b.id === id) ?? BRUSHES[0];
}
